# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: test actions

on:
  workflow_dispatch

env:
  tag: ${{github.ref_name}}-${{github.run_number}}

jobs:
  test-actions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project
    steps:
      - run: echo $TEST
      - uses: actions/checkout@v4
        with: 
          path: project
      - uses: actions/checkout@v4
        with:
          path: project2
          repository: sheshanth/bala
      - name: list dir items
        run: ls -la
      - name: list all project
        run : ls -la ../
      - name: pwd
        run: pwd
      - name: ref name
        run: echo "$tag"
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - run: echo $VERSION
